CREATE TABLE USER (ID VARCHAR(32), USERNAME VARCHAR(100),PASSWORD VARCHAR(100) );

INSERT INTO USER (ID, USERNAME ,PASSWORD) VALUES (1, '薇恩','vvnn');
INSERT INTO USER (ID, USERNAME,PASSWORD) VALUES (2, '乐芙兰','llff');
INSERT INTO USER (ID, USERNAME,PASSWORD) VALUES (3, '盲僧','mmss');
INSERT INTO USER (ID, USERNAME,PASSWORD) VALUES (4, '墨菲特','mmff');